name: Trigger Repo B

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  notify-repo-b:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Repo B workflow
        env:
          GH_TOKEN: ${{ secrets.TESTING_REPO_TOKEN }}
        run: |
          echo "Triggering Repo B workflow..."
          curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.TESTING_REPO_TOKEN }}" https://api.github.com/repos/VonWebsterLabajo/testing-demo/dispatches -d '{"event_type":"trigger-from-calculator-demo"}'